2018-05-25 07:32:35.526 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.164.0> exit with reason normal in context child_terminated
2018-05-25 07:32:35.590 [error] <0.215.0>@Elixir.Procon.Application:start_erl_kaf:23 CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: no match of right hand value [{bootstrap_servers,<<"localhost:9092">>},{delivery_report_only_error,false},{delivery_report_callback,#Fun<Elixir.Procon.Application.0.83746866>}] in 'Elixir.Procon.Application':start_erl_kaf/0 line 23 in application_master:init/4 line 134
2018-05-25 07:33:10.649 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 07:33:10.709 [error] <0.192.0>@Elixir.Procon.Application:start_erl_kaf:23 CRASH REPORT Process <0.192.0> with 0 neighbours exited with reason: no match of right hand value [{bootstrap_servers,<<"localhost:9092">>},{delivery_report_only_error,false},{delivery_report_callback,#Fun<Elixir.Procon.Application.0.83746866>}] in 'Elixir.Procon.Application':start_erl_kaf/0 line 23 in application_master:init/4 line 134
2018-05-25 07:34:00.554 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 07:34:00.609 [error] <0.192.0>@Elixir.Procon.Application:start CRASH REPORT Process <0.192.0> with 0 neighbours exited with reason: bad return value [{bootstrap_servers,<<"localhost:9092">>},{delivery_report_only_error,false},{delivery_report_callback,#Fun<Elixir.Procon.Application.0.113779979>}] from 'Elixir.Procon.Application':start(normal, []) in application_master:init/4 line 134
2018-05-25 07:34:20.441 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 09:41:50.567 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 09:41:51.696 [error] <0.194.0>@erlkaf_producer:handle_info:83 #Fun<Elixir.Procon.Application.0.102247880>:delivery_report error: {'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {erlkaf_msg,<<"refresh_events">>,2,0,<<"azer">>,<<"coucou">>}},[{'Elixir.String.Chars','impl_for!',1,[{file,"/private/tmp/elixir-20180507-68757-17gx35t/elixir-1.6.5/lib/elixir/lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"/private/tmp/elixir-20180507-68757-17gx35t/elixir-1.6.5/lib/elixir/lib/string/chars.ex"},{line,22}]},{'Elixir.Procon.Application',delivery_report,2,[{file,"lib/procon/application.ex"},{line,34}]},{erlkaf_producer,handle_info,2,[{file,"/Users/ceissen/labs/papayecube/procon/procon/deps/erlkaf/src/erlkaf_producer.erl"},{line,79}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}
2018-05-25 09:45:23.639 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 09:45:24.744 [error] <0.194.0>@erlkaf_producer:handle_info:83 #Fun<Elixir.Procon.Application.0.53185462>:delivery_report error: {'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {erlkaf_msg,<<"refresh_events">>,2,1,<<"azer">>,<<"coucou">>}},[{'Elixir.String.Chars','impl_for!',1,[{file,"/private/tmp/elixir-20180507-68757-17gx35t/elixir-1.6.5/lib/elixir/lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"/private/tmp/elixir-20180507-68757-17gx35t/elixir-1.6.5/lib/elixir/lib/string/chars.ex"},{line,22}]},{'Elixir.Procon.Application',delivery_report,2,[{file,"lib/procon/application.ex"},{line,34}]},{erlkaf_producer,handle_info,2,[{file,"/Users/ceissen/labs/papayecube/procon/procon/deps/erlkaf/src/erlkaf_producer.erl"},{line,79}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}
2018-05-25 09:47:48.701 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 09:47:49.796 [error] <0.194.0>@erlkaf_producer:handle_info:83 #Fun<Elixir.Procon.Application.0.83072852>:delivery_report error: {erlkaf_msg,<<"refresh_events">>,2,2,<<"azer">>,<<"coucou">>}
2018-05-25 09:48:29.728 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:08:11.024 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:08:42.199 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:08:59.700 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:09:00.795 [error] <0.194.0>@erlkaf_producer:handle_info:83 #Fun<Elixir.Procon.Application.0.83072852>:delivery_report error: {erlkaf_msg,<<"refresh_events">>,2,6,<<"azer">>,<<"coucou">>}
2018-05-25 10:29:30.624 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:29:31.741 [error] <0.194.0>@erlkaf_producer:handle_info:83 #Fun<Elixir.Procon.Application.0.59063235>:delivery_report error: <<"refresh_events">>
2018-05-25 10:30:19.944 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:30:38.880 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-28 10:19:11.641 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 10:19:11.729 [error] <0.270.0>@gen_tcp:connect:149 CRASH REPORT Process <0.270.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-28 10:20:26.041 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 10:21:18.154 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:48:37.436 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:49:28.140 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:49:28.246 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 14:50:05.781 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:52:40.032 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:58:25.320 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:58:25.419 [error] <0.268.0>@Elixir.List:keyfind:265 CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: bad argument in call to lists:keyfind(topic_metadata, 1, {kafka_metadata,[{brokers,[[{node_id,0},{host,<<"localhost">>},{port,9092},{rack,undefined}]]},{...},...]}) in 'Elixir.List':keyfind/4 line 265 in application_master:init/4 line 134
2018-05-28 14:59:43.799 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:59:43.908 [error] <0.268.0>@Elixir.List:keyfind:265 CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: bad argument in call to lists:keyfind(topic_metadata, 1, {kafka_metadata,[{brokers,[[{node_id,0},{host,<<"localhost">>},{port,9092},{rack,undefined}]]},{...},...]}) in 'Elixir.List':keyfind/4 line 265 in application_master:init/4 line 134
2018-05-28 15:00:43.251 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:00:43.375 [error] <0.268.0>@Elixir.List:keyfind CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic) in application_master:init/4 line 134
2018-05-28 15:01:08.282 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:01:08.397 [error] <0.268.0>@Elixir.List:keyfind CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic) in application_master:init/4 line 134
2018-05-28 15:01:32.106 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:01:32.221 [error] <0.268.0>@Elixir.List:keyfind CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic) in application_master:init/4 line 134
2018-05-28 15:02:16.370 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:02:16.494 [error] <0.268.0>@Elixir.List:keyfind CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic) in application_master:init/4 line 134
2018-05-28 15:03:06.391 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:03:06.514 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 15:03:38.119 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:03:38.237 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 15:04:50.757 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:04:50.875 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 15:05:29.064 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:05:29.193 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 15:05:46.766 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:05:46.900 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 15:06:37.175 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:41:26.112 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:42:46.236 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:45:04.795 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:53:55.275 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 16:28:18.280 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:22:56.367 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:24:04.303 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:26:10.455 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:28:02.871 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:29:06.372 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:34:00.302 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:38:55.589 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 22:04:15.984 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 22:04:22.839 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 09:31:19.195 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 22:22:57.728 [error] <0.189.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.194.0> exit with reason normal in context child_terminated
2018-05-29 22:22:57.844 [error] <0.283.0>@gen_tcp:connect:149 CRASH REPORT Process <0.283.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:22:57.881 [error] <0.282.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:22:57.881 [error] <0.282.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:22:57.882 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.282.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:07.845 [error] <0.288.0>@gen_tcp:connect:149 CRASH REPORT Process <0.288.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:07.847 [error] <0.287.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:07.847 [error] <0.287.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:07.847 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.287.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:17.847 [error] <0.290.0>@gen_tcp:connect:149 CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:17.848 [error] <0.289.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:17.848 [error] <0.289.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:17.848 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.289.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:27.847 [error] <0.292.0>@gen_tcp:connect:149 CRASH REPORT Process <0.292.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:27.849 [error] <0.291.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:27.849 [error] <0.291.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:27.849 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.291.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:37.849 [error] <0.294.0>@gen_tcp:connect:149 CRASH REPORT Process <0.294.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:37.850 [error] <0.293.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:37.850 [error] <0.293.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:37.850 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.293.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:47.850 [error] <0.296.0>@gen_tcp:connect:149 CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:47.851 [error] <0.295.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:47.851 [error] <0.295.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:47.851 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.295.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:57.851 [error] <0.298.0>@gen_tcp:connect:149 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:57.852 [error] <0.297.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:57.852 [error] <0.297.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:57.853 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.297.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:24:07.852 [error] <0.300.0>@gen_tcp:connect:149 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:24:07.853 [error] <0.299.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:24:07.853 [error] <0.299.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:24:07.854 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.299.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:24:17.853 [error] <0.302.0>@gen_tcp:connect:149 CRASH REPORT Process <0.302.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:24:17.854 [error] <0.301.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:24:17.854 [error] <0.301.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:24:17.854 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.301.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:24:21.849 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 22:25:32.611 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 22:28:55.667 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 22:34:52.077 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 22:35:17.831 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:16:27.304 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:18:00.149 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:20:32.650 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:23:20.716 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:23:41.321 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:26:28.759 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:27:06.655 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:27:06.831 [error] <0.280.0>@brod_utils:bytes:492 gen_server <0.280.0> terminated with reason: no function clause matching brod_utils:bytes(256) line 492
2018-05-29 23:27:06.831 [error] <0.280.0>@brod_utils:bytes:492 CRASH REPORT Process <0.280.0> with 0 neighbours crashed with reason: no function clause matching brod_utils:bytes(256) line 492
2018-05-29 23:27:06.831 [error] <0.277.0>@brod_utils:bytes:492 Supervisor {<0.277.0>,brod_producers_sup} had child 2 started with brod_producer:start_link(<0.273.0>, <<"refresh_events">>, 2, []) at <0.280.0> exit with reason no function clause matching brod_utils:bytes(256) line 492 in context child_terminated
2018-05-29 23:27:27.889 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:27:28.041 [error] <0.280.0>@kpro:encode:297 gen_server <0.280.0> terminated with reason: no function clause matching kpro:encode(bytes, 1) line 297
2018-05-29 23:27:28.042 [error] <0.280.0>@kpro:encode:297 CRASH REPORT Process <0.280.0> with 0 neighbours crashed with reason: no function clause matching kpro:encode(bytes, 1) line 297
2018-05-29 23:27:28.042 [error] <0.277.0>@kpro:encode:297 Supervisor {<0.277.0>,brod_producers_sup} had child 2 started with brod_producer:start_link(<0.273.0>, <<"refresh_events">>, 2, []) at <0.280.0> exit with reason no function clause matching kpro:encode(bytes, 1) line 297 in context child_terminated
2018-05-29 23:28:00.470 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:28:14.633 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:28:51.328 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:29:19.785 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:29:21.149 [error] <0.280.0> Error in produce response
Topic: refresh_events Partition: 2 Offset: -1 Error: 'MessageTooLarge'
2018-05-29 23:29:21.217 [error] <0.280.0> gen_server <0.280.0> terminated with reason: {not_retriable,{produce_response_error,<<"refresh_events">>,2,-1,'MessageTooLarge'}} in brod_producer:handle_info/2 line 317
2018-05-29 23:29:21.217 [error] <0.280.0> CRASH REPORT Process <0.280.0> with 0 neighbours exited with reason: {not_retriable,{produce_response_error,<<"refresh_events">>,2,-1,'MessageTooLarge'}} in brod_producer:handle_info/2 line 317
2018-05-29 23:29:21.217 [error] <0.277.0> Supervisor {<0.277.0>,brod_producers_sup} had child 2 started with brod_producer:start_link(<0.273.0>, <<"refresh_events">>, 2, []) at <0.280.0> exit with reason {not_retriable,{produce_response_error,<<"refresh_events">>,2,-1,'MessageTooLarge'}} in context child_terminated
